receive_data:
  ros__parameters:
    max_history_size: 4.0       #记录最大的历史步数
    smoothing_factor: 0.8       #光滑因子
    max_position_jump: 30.0     #最大跳转像素
    min_time_interval: 0.03     #最小时间间隔 （ms）
    pid_parameters_p: 10.0       #PID 比率
    pid_parameters_i: 0.1       #PID 积分
    pid_parameters_d: 0.2       #PID 微分
    history_weight_factor: 0.3  #历史权重因子  0-1 值越大越相信当前速度
    max_integral: 40.0         #积分上限
    estimator_rate_: 1.0        #图像速度转换比率
    estimator_dt_: 10.0          #最后转出的距离

    nms_threshold_: 0.4         #nms最大抑制
    confidence_threshold_: 0.5  #正确率最低值
    detector: "../model/best.onnx"










