receive_data:
  ros__parameters:
    nms_threshold_: 0.4  #nms最大抑制
    confidence_threshold_: 0.5  #正确率最低值
    detector : "../model/best.onnx"

tf_publisher:
  ros__parameters:
    height : 1.5
    tf2_reflash_num : 5

